/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoGuitarchatRouteImport } from './routes/demo/guitarchat'
import { Route as ExampleGuitarsIndexRouteImport } from './routes/example/guitars/index'
import { Route as ExampleGuitarsGuitarIdRouteImport } from './routes/example/guitars/$guitarId'
import { Route as DemoApiTtsRouteImport } from './routes/demo/api.tts'
import { Route as DemoApiGuitarchatRouteImport } from './routes/demo/api.guitarchat'
import { Route as DemoApiAvailableProvidersRouteImport } from './routes/demo/api.available-providers'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoGuitarchatRoute = DemoGuitarchatRouteImport.update({
  id: '/demo/guitarchat',
  path: '/demo/guitarchat',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleGuitarsIndexRoute = ExampleGuitarsIndexRouteImport.update({
  id: '/example/guitars/',
  path: '/example/guitars/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleGuitarsGuitarIdRoute = ExampleGuitarsGuitarIdRouteImport.update({
  id: '/example/guitars/$guitarId',
  path: '/example/guitars/$guitarId',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiTtsRoute = DemoApiTtsRouteImport.update({
  id: '/demo/api/tts',
  path: '/demo/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiGuitarchatRoute = DemoApiGuitarchatRouteImport.update({
  id: '/demo/api/guitarchat',
  path: '/demo/api/guitarchat',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiAvailableProvidersRoute =
  DemoApiAvailableProvidersRouteImport.update({
    id: '/demo/api/available-providers',
    path: '/demo/api/available-providers',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/demo/guitarchat': typeof DemoGuitarchatRoute
  '/demo/api/available-providers': typeof DemoApiAvailableProvidersRoute
  '/demo/api/guitarchat': typeof DemoApiGuitarchatRoute
  '/demo/api/tts': typeof DemoApiTtsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/example/guitars': typeof ExampleGuitarsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/demo/guitarchat': typeof DemoGuitarchatRoute
  '/demo/api/available-providers': typeof DemoApiAvailableProvidersRoute
  '/demo/api/guitarchat': typeof DemoApiGuitarchatRoute
  '/demo/api/tts': typeof DemoApiTtsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/example/guitars': typeof ExampleGuitarsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/demo/guitarchat': typeof DemoGuitarchatRoute
  '/demo/api/available-providers': typeof DemoApiAvailableProvidersRoute
  '/demo/api/guitarchat': typeof DemoApiGuitarchatRoute
  '/demo/api/tts': typeof DemoApiTtsRoute
  '/example/guitars/$guitarId': typeof ExampleGuitarsGuitarIdRoute
  '/example/guitars/': typeof ExampleGuitarsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/demo/guitarchat'
    | '/demo/api/available-providers'
    | '/demo/api/guitarchat'
    | '/demo/api/tts'
    | '/example/guitars/$guitarId'
    | '/example/guitars'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/demo/guitarchat'
    | '/demo/api/available-providers'
    | '/demo/api/guitarchat'
    | '/demo/api/tts'
    | '/example/guitars/$guitarId'
    | '/example/guitars'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/demo/guitarchat'
    | '/demo/api/available-providers'
    | '/demo/api/guitarchat'
    | '/demo/api/tts'
    | '/example/guitars/$guitarId'
    | '/example/guitars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  DemoGuitarchatRoute: typeof DemoGuitarchatRoute
  DemoApiAvailableProvidersRoute: typeof DemoApiAvailableProvidersRoute
  DemoApiGuitarchatRoute: typeof DemoApiGuitarchatRoute
  DemoApiTtsRoute: typeof DemoApiTtsRoute
  ExampleGuitarsGuitarIdRoute: typeof ExampleGuitarsGuitarIdRoute
  ExampleGuitarsIndexRoute: typeof ExampleGuitarsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/guitarchat': {
      id: '/demo/guitarchat'
      path: '/demo/guitarchat'
      fullPath: '/demo/guitarchat'
      preLoaderRoute: typeof DemoGuitarchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/guitars/': {
      id: '/example/guitars/'
      path: '/example/guitars'
      fullPath: '/example/guitars'
      preLoaderRoute: typeof ExampleGuitarsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/guitars/$guitarId': {
      id: '/example/guitars/$guitarId'
      path: '/example/guitars/$guitarId'
      fullPath: '/example/guitars/$guitarId'
      preLoaderRoute: typeof ExampleGuitarsGuitarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/tts': {
      id: '/demo/api/tts'
      path: '/demo/api/tts'
      fullPath: '/demo/api/tts'
      preLoaderRoute: typeof DemoApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/guitarchat': {
      id: '/demo/api/guitarchat'
      path: '/demo/api/guitarchat'
      fullPath: '/demo/api/guitarchat'
      preLoaderRoute: typeof DemoApiGuitarchatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/available-providers': {
      id: '/demo/api/available-providers'
      path: '/demo/api/available-providers'
      fullPath: '/demo/api/available-providers'
      preLoaderRoute: typeof DemoApiAvailableProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  DemoGuitarchatRoute: DemoGuitarchatRoute,
  DemoApiAvailableProvidersRoute: DemoApiAvailableProvidersRoute,
  DemoApiGuitarchatRoute: DemoApiGuitarchatRoute,
  DemoApiTtsRoute: DemoApiTtsRoute,
  ExampleGuitarsGuitarIdRoute: ExampleGuitarsGuitarIdRoute,
  ExampleGuitarsIndexRoute: ExampleGuitarsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
